name: notes_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  firebase_auth: ^5.5.4
  firebase_core: ^3.13.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  freezed_annotation: ^2.4.4
  google_fonts: ^6.2.1
  google_sign_in: ^6.3.0
  http: ^1.4.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2

dev_dependencies:

  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.8

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/image/
    - assets/icon/
